name: JSON Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check and Sort JSON
      run: |
        python ./validate_json.py  

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dapplist.json  
        git commit -m "Validate and sort JSON data" -a || echo "No changes to commit"
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/btclayer2/ecosystem.git main
