name: JSON Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up git context
      uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{ secrets.C_ACCESS_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check and Sort JSON
      run: |
        python ./validate_json.py  

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add dapplist.json  
        git commit -m "Validate and sort JSON data" -a || echo "No changes to commit"
        git push origin main
